dist: bionic
language: python
python:
  - 3.8
install:
  - cd test
  - docker-compose build
  - docker-compose up -d
  - cd ..
  - pip install pandas
  - pip install requests
script:
  - pwd
  - python -m unittest discover -s test -p "test_*.py"
